In [1]:
import pandas as pd
import numpy as np

In [2]:
l=[]
f = open("imdb_trainX.txt",encoding="utf8")
for x in f.readlines():
    x=x.replace("<br />","")
    x=x.replace("\n","")
    l.append(x)
df=pd.DataFrame(l,columns=["Review"])
l=[]
f = open("imdb_trainY.txt", encoding="utf8")
for x in f.readlines():
    #x=x.replace("\n","")
    l.append(int(x))
df["Rating"]=l

df.head()

Review  Rating
0  I loved this movie since I was 7 and I saw it ...      10
1  First things first, Edison Chen did a fantasti...       8
2  Once again, I was browsing through the discoun...       7
3  This is a gem, a real piece of Americana for a...       8
4  While I had wanted to se this film since the f...       8

In [3]:
df["Review"][0]

"I loved this movie since I was 7 and I saw it on the opening day. It was so touching and beautiful. I strongly recommend seeing for all. It's a movie to watch with your family by far.My MPAA rating: PG-13 for thematic elements, prolonged scenes of disastor, nudity/sexuality and some language."

In [4]:
from nltk.tokenize import RegexpTokenizer
tokenizer=RegexpTokenizer('[a-zA-Z]+')
from nltk.corpus import stopwords
sw=set(stopwords.words('english'))
sw.add("It")
sw.add("I")
sw.add("it")
sw.remove("not")
from nltk.stem.snowball import PorterStemmer
ps=PorterStemmer()

In [5]:
def textcleaner(l):
    words=[]
    sents=[]
    for i in range(len(l)):
        l[i]=(tokenizer.tokenize(l[i]))
        l[i]=[w for w in l[i] if w not in sw]
        for j in range(len(l[i])):
            l[i][j]=ps.stem(l[i][j])
        sents.append(" ".join(l[i]))
    words=[]
    return sents

In [6]:
sents=textcleaner(df["Review"])
print(sents[0])

ipykernel_launcher:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
ipykernel_launcher:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
love movi sinc saw open day touch beauti strongli recommend see movi watch famili far My mpaa rate PG themat element prolong scene disastor nuditi sexual languag


In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
vc=cv.fit_transform(sents[:100]).toarray()
print(vc)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [20]:
print(cv.vocabulary_)

effrey': 1820, 'comb': 670, 'anton': 148, 'mordrid': 2238, 'fantasi': 1221, 'fare': 1224, 'chees': 571, 'gore': 1464, 'fell': 1243, 'goldsworthi': 1456, 'warm': 3735, 'dirt': 943, 'broken': 414, 'fingernail': 1277, 'respond': 2831, 'rap': 2731, 'cube': 809, 'band': 249, 'solo': 3158, 'dr': 998, 'dre': 1005, 'spree': 3223, 'explain': 1179, 'booti': 364, 'juic': 1849, 'polit': 2588, 'statement': 3249, 'hilari': 1602, 'tasti': 3397, 'vanilla': 3661, 'sherbert': 3051, 'ass': 195, 'record': 2768, 'bachelor': 238, 'parti': 2479, 'coleman': 660, 'jason': 1817, 'dancer': 832, 'becki': 284, 'julia': 1851, 'stile': 3267, 'drink': 1011, 'wake': 3721, 'fianc': 1257, 'karen': 1860, 'selma': 2997, 'blair': 330, 'desper': 907, 'hurri': 1667, 'sooner': 3175, 'crab': 771, 'prepar': 2631, 'wed': 3760, 'dinner': 937, 'cousin': 766, 'trio': 3558, 'drugstor': 1018, 'explan': 1180, 'medicin': 2149, 'minist': 2194, 'reader': 2748, 'vote': 3716, 'seven': 3026, 'louco': 2040, 'por': 2597, 'ela': 1067, 'them': 

In [21]:
vc.shape

(100, 3880)

In [22]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB

In [32]:
mnb=BernoulliNB()
print(mnb)

BernoulliNB()


In [33]:
mnb.fit(vc,df["Rating"][:100])

BernoulliNB()

In [42]:
xtest=cv.transform(sents[173:175]).toarray()
print(xtest)
print(mnb.predict(xtest))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[10 10]


In [43]:
df["Rating"][173:175]

173    7
174    9
Name: Rating, dtype: int64

In [44]:
mnb.predict_proba(xtest)

array([[2.42934827e-47, 4.07537958e-24, 1.63323512e-83, 1.00000000e+00],
       [2.00005903e-41, 6.42658310e-20, 3.55685145e-73, 1.00000000e+00]])